default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: notebook
  password: wYI0C4bcZz1MVWHm3T1N5TlRjaST9sdY
  host: dpg-d0o1jqili9vc73filkt0-a.oregon-postgres.render.com
  port: 5432
  database: notebook_372o

development:
  <<: *default

test:
  <<: *default
  database: notebook_test  # tu peux créer une base test séparée

production:
  <<: *default
